#!/bin/sh
DIR=`dirname "$0"`
cd "$DIR" || exit 1

"$DIR/java" \
  -XX:+UseG1GC \
  -Djavafx.enablePreview=true \
  -Djavafx.suppressPreviewWarning=true \
  --enable-final-field-mutation=com.sun.jna \
  --enable-native-access=javafx.graphics,com.github.kwhat.jnativehook,com.sun.jna,org.bytedeco.javacpp,org.bytedeco.opencv,org.bytedeco.leptonica,org.bytedeco.tesseract \
  -m priv.koishi.pmc/priv.koishi.pmc.MainApplication \
  "$@"